### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by Ir1d** [OpenKikCoc/cp-wiki#1]
Hi @BinacsLee ,

It's great to see some new endeavor contributing to the community of competitive programming. However, we're concerned that you're using a lot of material from OI Wiki without proper crediting.

Note that contents in OI Wiki are mostly licensed under CC-BY-SA.
Please kindly consider following our license. We'd also like to invite you to join in contributing to OI Wiki as well. Together We Can Make A Difference.

Best,

**Comment by binacs** [comment]
> 为了避免词不达意引起的其他问题，我直接在这里用中文回复。

@Ir1d  非常感谢您的提醒，我必须为我的疏忽真诚致歉。

这个 repo 的起因是想要更系统地整理 Luogu / LeetCode / AcWing 上做过的一些题目，同时挂个 GitHub Pages 方便利用上下班通勤路上的时间复习。*（地铁信号极差，基本无法上网，所以这个 repo 使用了 docsify 而非其他框架以便进地铁之前提前打开并缓存、在途中没信号的时候可以离线浏览包括切不同的目录）*

再次为此前的疏忽道歉。我非常喜欢 oi-wiki 的知识框架，也敬重各位前辈在社区的贡献。也正因此，才基于 oi-wiki 的目录结构做了现在的这些题目的补充。我的本意并非搬运 oi-wiki ，如前一段所述，我做这个事情的本质是想系统地整理学过的内容。因为消化了的知识才是自己的知识，我更希望的是有一天我可以在这个知识体系下使用更简短且对我个人来说更容易理解和记忆的方式记录下来。

但平时的时间确实被工作挤压的比较严重，我已经尽可能地尝试去提高工作效率并在算法、开源社区等等方面去规划和分配时间，但完成 repo 中更个人的总结而非一个简单地复制粘贴仍然需要相当长的一段时间。**当然，这仍然不是我忽略了 License 问题的理由，我已经提交了新的内容以把 oi-wiki 的 repo 与 License 一并附在 README 文档中，并对本 repo 的目的做更进一步的说明。**

如果有机会，我很乐意能够参与到 oi-wiki 的建设中去。只是我的水平有限，在【写一个大多数人能看懂的好文章】方面可能很难做出贡献。而在题目扩充方面，本 repo 里的相当一部分 LeetCode 的基础题目对于 oi 选手来说可能也比较鸡肋（换个说法就是，题目总结感觉是一个更个人的东西，我比较难做到把我个人期望的复习内容完全放在 oi-wiki ... 毕竟这些内容重口难调）。**但是如果是在容器化或者云原生方面需要协助，我希望能贡献自己微不足道的力量。**

再次致歉。如果对我的处理措施有任何意见或建议，也希望能够直接和我沟通和交流，我会积极地处理这些事情 ^ ^

**Comment by Ir1d** [comment]
感谢您的理解与支持，“水平有限" 实在是太谦虚了hhh
